-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:ARZ ARZOPA-27",
  mode = "2560x1440@60.00",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Display Corp. 0x41B5",
  mode = "1920x1200@60.00",
  position = "0x200",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. 0x41B5", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Display Corp. 0x41B5" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Display Corp. 0x41B5" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Samsung Display Corp. 0x41B5" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Display Corp. 0x41B5" })
hl.workspace_rule({ workspace = "6", monitor = "desc:ARZ ARZOPA-27", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:ARZ ARZOPA-27" })
hl.workspace_rule({ workspace = "8", monitor = "desc:ARZ ARZOPA-27" })
hl.workspace_rule({ workspace = "9", monitor = "desc:ARZ ARZOPA-27" })
hl.workspace_rule({ workspace = "10", monitor = "desc:ARZ ARZOPA-27" })
