##############################
### TAGGING ##################
##############################

windowrule = tag +games, match:class ^(steam_app_\d+)$
windowrule = tag +games, match:class ^(gamescope)$

windowrule = tag +utility, match:class ^(blueman-manager)$
windowrule = tag +utility, match:class ^(pavucontrol-qt)$
windowrule = tag +utility, match:class ^(org.kde.plasma-systemmonitor)$
windowrule = tag +utility, match:class ^(org.freedesktop.impl.portal.desktop.kde)$

windowrule = tag +utility, match:title ^(Save Image — Gwenview)$
windowrule = tag +utility, match:class ^(xdg-desktop-portal-gtk)$
windowrule = tag +utility, match:class ^(org.kde.dolphin)$
windowrule = tag +utility, match:class ^(yazi-filechooser)$
windowrule = tag +utility, match:class ^(yazi)$


##############################
### GAME RULES ###############
##############################

windowrule = idle_inhibit always, fullscreen on, opacity 1.0 override, rounding 0, workspace 6, match:tag games


##############################
### UTILITY RULES ############
##############################

windowrule = float on, size (monitor_w*0.5) (monitor_h*0.5), match:tag utility


##############################
### APP-SPECIFIC #############
##############################

windowrule = workspace 5 silent, match:class ^(.*Spotify.*)$
windowrule = workspace 6 silent, match:class ^(.*steam.*)$


##############################
### LAYER RULES ##############
##############################

layerrule = blur on, match:namespace namespace:logout_dialog
layerrule {
  name = blur-waybar
  blur = on
  ignore_alpha = 0
  match:namespace = waybar
}