##############################
### TAGGING ##################
##############################

windowrule = tag +games, match:class ^(steam_app_\d+)$
windowrule = tag +games, match:class ^(gamescope)$

windowrule = tag +utility, match:class ^(blueman-manager)$
windowrule = tag +utility, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = tag +utility, match:class ^(org.kde.plasma-systemmonitor)$
windowrule = tag +utility, match:title ^(Save Image — Gwenview)$


##############################
### GAME RULES ###############
##############################

windowrule = idle_inhibit always, fullscreen on, opacity 1.0 override, rounding 0, workspace 6, match:tag games


##############################
### UTILITY RULES ############
##############################

windowrule = float on, size (monitor_w*0.5) (monitor_h*0.5), match:tag utility


##############################
### APP-SPECIFIC #############
##############################

windowrule = workspace 5 silent, match:class ^(.*spotify.*)$
windowrule = workspace 6 silent, match:class ^(.*steam.*)$


##############################
### LAYER RULES ##############
##############################

layerrule = blur on, match:namespace namespace:logout_dialog
