source = colors.conf

# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

$battery= ~/.config/hypr/hyprlock/scripts/battery.sh


background {
    monitor =
    path = screenshot
    blur_size = 5
    blur_passes = 3
    brightness = .6
}



label {
    monitor =
    text = cmd[update:1000] date +"<b>%I</b>"
    color = $primary
    font_size = 200
    font_family = CodeNewRoman Nerd Font Propo
    shadow_passes = 0
    shadow_size = 5
    position = -120, 410
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%M</b>"
    color = $tertiary
    font_size = 200
    font_family = CodeNewRoman Nerd Font Propo
    shadow_passes = 0
    shadow_size = 5
    position = 120, 230
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%A %d %B, %Y</b>"
    color = $on_background
    font_size = 40
    font_family = CodeNewRoman Nerd Font Propo
    shadow_passes = 0
    shadow_size = 4
    position = -40,-20
    halign = right
    valign = top
}

label {
    monitor =
    text = <i>Hello</i> <b>$USER</b>
    color = $on_background 
    font_size = 40
    font_family = CodeNewRoman Nerd Font Propo
    shadow_passes = 0
    shadow_size = 4
    position = 40,-20
    halign = left
    valign = top
}

# INPUT FIELD
input-field {
    monitor =
    size = 13%, 5%
    outline_thickness = 2
    inner_color = $surface_bright 
    check_color=$outline
    outer_color=$primary $tertiary 120deg
    fail_color=rgba(255,0,0,0)
    fail_text=<b> WRONG </b>
    placeholder_text = <i> Fill me </i>
    font_color = $on_surface_variant
    fade_on_empty = false
    rounding = 15

    position = 0, -60
    halign = center
    valign = center
}

# CAPSLOCK ICON OVERLAY
label {
    monitor =
    text = cmd[update:500] ~/.config/hypr/hyprlock/scripts/capslock.sh
    color = $primary
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    position = -100, -60
    halign = center
    valign = center
    zindex = 5
}

# Battery div
shape {
    monitor =
    size = 140, 80
    color =$primary
    rounding = 20
    rotate = 0
    position = 0, 25
    halign = center
    valign = bottom
    zindex = 1
}

# Battery
label {
    monitor =
    text = cmd[update:1000] echo -e "$($battery)"
    color = $on_primary
    font_size = 25
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, 45
    halign = center
    valign = bottom
    zindex = 5
}

# ==== Power menu  ====

# BOUTON : SLEEP 
label {
    monitor =
    text = <span> 󰒲 </span>
    onclick = systemctl suspend
    color = $on_background
    font_size = 25
    font_family = JetBrains Mono Nerd Font
    position = -30, 170
    halign = right
    valign = bottom
    zindex = 5
}

# BOUTON : REBOOT (Redémarrer)
label {
    monitor =
    text = <span> 󰑓 </span>
    onclick = systemctl reboot
    color = $on_background
    font_size = 25
    font_family = JetBrains Mono Nerd Font
    position = -30, 100
    halign = right
    valign = bottom
    zindex = 5
}

# BOUTON : SHUTDOWN (Éteindre)
label {
    monitor =
    text = <span>  </span>
    onclick = systemctl poweroff
    color = $on_background 
    font_size = 25
    font_family = JetBrains Mono Nerd Font
    position = -30, 30
    halign = right
    valign = bottom
    zindex = 5
}